name: CMake Multi-Platform Build

on:
  push:
    branches: [ "main", "master" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install TBB (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libtbb-dev

    # Use the official Microsoft vcpkg action
    - name: Setup vcpkg
      uses: microsoft/vcpkg-action@v1
      with:
        pkgs: argparse
        vcpkgGitCommitId: '8049926c8be40b973b1373e6d6b1d129705df82c'

    - name: Configure CMake
      run: >
        cmake -B build -S .
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-binaries
        path: |
          build/fuzzy-ctph
          build/Release/fuzzy-ctph.exe
        if-no-files-found: warn

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-files
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release-files/fuzzy-ctph.exe
            ./release-files/fuzzy-ctph
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}